### PR TITLE
Upgrade to Clang/LLVM 10.0.1

### PR DESCRIPTION
**Pull request by qiao-bo**

### CODE REVIEW

**Comment by oreiche** [comment]
@qiao-bo Oh, you'll need to create new Docker images for this PR, as the images contain a pre-built Clang distribution... :/

**Comment by qiao-bo** [comment]
> @qiao-bo Oh, you'll need to create new Docker images for this PR, as the images contain a pre-built Clang distribution... :/

yes, im working on that. thanks

**Comment by qiao-bo** [comment]
> @qiao-bo Oh, you'll need to create new Docker images for this PR, as the images contain a pre-built Clang distribution... :/

@oreiche, is the pre-built binary "llvm-8.0.1-minimal.tgz" downloaded from [here]{https://releases.llvm.org/download.html}? did not find any name with minimal ...

**Review by oreiche — CHANGES_REQUESTED** [review]
@qiao-bo Could you do me a favor and rebase this branch once you finished? Particularly, combine commits a546e2bd9d1d6c71db1e852eca79291e02636599 and 329fb848b06094a9bde0e4bcec738d37665d1a78, as well as 7a0951d97733f94dfb7ff4d4b6d72b74685e5bd7 and 5d764f0bfed694f7f72353c68dd5ebaa195b1a70.

**Comment by qiao-bo** [comment]
> @qiao-bo Could you do me a favor and rebase this branch once you finished? Particularly, combine commits [a546e2b](https://github.com/hipacc/hipacc/commit/a546e2bd9d1d6c71db1e852eca79291e02636599) and [329fb84](https://github.com/hipacc/hipacc/commit/329fb848b06094a9bde0e4bcec738d37665d1a78), as well as [7a0951d](https://github.com/hipacc/hipacc/commit/7a0951d97733f94dfb7ff4d4b6d72b74685e5bd7) and [5d764f0](https://github.com/hipacc/hipacc/commit/5d764f0bfed694f7f72353c68dd5ebaa195b1a70).

@oreiche, Hi, yes, i can rebase the redundant commits. i am looking into the windows build now, slowly...

**Review by oreiche — APPROVED** [review]
Looks good to me!

**Pull request merged**
